---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app-container
          image: docravin/blogapp:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: jenkins-secret

---
apiVersion: v1
kind: Service
metadata:
  name: blog-app-svc
spec:
  selector:
    app: blog-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
