---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app-container
          image: docravin/blogapp:v1
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
  #Make sure to execute the "kubectl create secret docker-registry jenkins-secret \
  # --docker-server=<DOCKER_REGISTRY_URL> \
  # --docker-username=<USERNAME> \
  # --docker-password=<PASSWORD> \
  # --docker-email=<EMAIL> \
  # --namespace=webapps" command to generate docker registry access token, Check Obsidian.

---
apiVersion: v1
kind: Service
metadata:
  name: blog-app-svc
spec:
  selector:
    app: blog-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
